# Generated by Django 3.0 on 2022-12-01 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20221201_0948'),
        ('lettings', '0002_auto_20221201_0950'),
        ('profiles', '0002_auto_20221201_1111')
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Letting',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
